(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Input::Initialization:: *)
K[z_, \[Tau]_] := E^(-z^2/\[Tau])/Sqrt[\[Pi] \[Tau]]
g[x_] := E^-x^2-Sqrt[\[Pi]]x Erfc[x];
NOwenS[h_?NumberQ,a_?NumberQ,b_?NumberQ]:=NIntegrate[OwenT[a x,b] E^(-(x^2/2))/Sqrt[2 \[Pi]],{x,-Infinity,h}];
ruleErf = Erf[x_] -> 1-Erfc[x];

ruleErfcM = Erfc[-x_]-> 2-Erfc[x];

ruleOwenS = OwenS[-h_, a_, b_]-> 1/(2\[Pi]) ArcTan[b/Sqrt[1+a^2+a^2 b^2]]-OwenS[h, a, b];


(* ::Input::Initialization:: *)
rulesT={\[Tau]1-> t1, \[Tau]2-> t2-t1, \[Tau]3-> t3-t2, \[Tau]4-> t4-t3};
rulesTau={t1-> \[Tau]1, t2-> \[Tau]1+\[Tau]2, t3-> \[Tau]1+\[Tau]2+\[Tau]3, t4-> \[Tau]1+\[Tau]2+\[Tau]3+\[Tau]4};
ruleA =  ArcTan[u_]-> \[Pi]/2 A[u^2];

$Assumptions={\[Tau]1>0, \[Tau]2>0, \[Tau]3>0,\[Tau]4>0, \[Tau]>0,t1>0,t2>0,t3>0,t4>0,\[Mu]1>0, \[Mu]2>0 ,\[Mu]3>0, \[Mu]4>0,z1>0,z2>0,z3>0,z4>0};


(* ::Input::Initialization:: *)
reverse[x_]:= Simplify[A[x]-> 1-A[1/x]];
combine1[x_, y_] := A[x]-> FullSimplify[A[Simplify[((Sqrt[x]+Sqrt[y])/(1-Sqrt[x y]))^2]]]-A[y](*x y > 0 *)
combine2[x_, y_] := A[x]->2- FullSimplify[A[Simplify[((Sqrt[1/x]+Sqrt[1/y])/(Sqrt[1/(x y)]-1))^2]]]-A[y] (* x y < 0 *)
combine[x_, y_]:= If[
Simplify@Sign@Factor[(Denominator[#]-Numerator[#])& @Simplify[x y]]>0,
combine1[x, y],
combine2[x, y],
Null]

combineR1[x_, y_, s1_, s2_]:=Simplify[Simplify[A[x]-> A[((Sqrt[x]+Sqrt[y])/(1-Sqrt[x y]))^2/.s2-> s1+\[Tau]]-A[y]]/.\[Tau]->s2-s1 ];
combineR2[x_, y_, s1_, s2_] := Simplify[Simplify[A[x]->2- A[((Sqrt[1/x]+Sqrt[1/y])/(Sqrt[1/(x y)]-1))^2/.s2-> s1+\[Tau]]-A[y]]/.\[Tau]->s2-s1];
combineR[x_, y_, s1_, s2_, rule_]:= If[
Simplify@Sign@Factor[(Denominator[#]-Numerator[#])& @Simplify[x y/.rule]]>0,
combineR1[x, y,s1, s2],
combineR2[x, y,s1, s2],
Null]

combineRSimp[x_, y_, s1_, s2_, rule_] := Simplify[Simplify[combineR[x, y, s1, s2, rule]/. rulesTau] /.rulesT]


(* ::Input::Initialization:: *)
Clear[integrate];

integrate[a_+b_, z_] := integrate[a, z] + integrate[b, z];
integrate[c_ f_, z_] := c integrate[f, z] /; FreeQ[c, z];

integrate[Exp[-\[Alpha]_. (z_-x_.)^2] | Exp[-\[Alpha]_. (x_-z_.)^2], z_]:=1/2 Sqrt[\[Pi]/\[Alpha]](1+Erf[x Sqrt[\[Alpha]]]);
integrate[Exp[-\[Alpha]_. (z_-x_.)^2] Erf[\[Beta]_. z_]|Exp[-\[Alpha]_. (x_.-z_)^2] Erf[\[Beta]_. z_],z_]:=1/2 Sqrt[\[Pi]/\[Alpha]]  (1+Erf[(x \[Alpha] \[Beta])/Sqrt[\[Alpha] (\[Alpha]+\[Beta]^2)]]-4 OwenT[(Sqrt[2] x \[Alpha] \[Beta])/Sqrt[\[Alpha] (\[Alpha]+\[Beta]^2)],Sqrt[\[Alpha]]/\[Beta]])/; Simplify[Positive[\[Beta]]];
integrate[Exp[-\[Alpha]_. (z_-x_.)^2] Erfc[\[Beta]_. z_]|Exp[-\[Alpha]_. (x_.-z_)^2] Erfc[\[Beta]_. z_],z_]:=1/2 Sqrt[\[Pi]/\[Alpha]] (-Erfc[x Sqrt[\[Alpha]]]+Erfc[x \[Beta] Sqrt[\[Alpha]/(\[Alpha]+\[Beta]^2)]]+4 OwenT[Sqrt[2] x \[Beta] Sqrt[\[Alpha]/(\[Alpha]+\[Beta]^2)],Sqrt[\[Alpha]]/\[Beta]])/;Simplify[Positive[\[Beta]]];


(* ::Input::Initialization:: *)
integrate[Erfc[\[Alpha]_. z_],z_]:=1/(Sqrt[\[Pi]] \[Alpha])/; Simplify[Positive[\[Alpha]]];
integrate[Erfc[\[Alpha]_. z_]Erfc[\[Beta]_. z_],z_]:=(\[Alpha]+\[Beta]-Sqrt[\[Alpha]^2+\[Beta]^2])/(Sqrt[\[Pi]] \[Alpha] \[Beta])/; Simplify[Positive[\[Alpha]]&&Positive[\[Beta]]];
integrate[Erfc[\[Alpha]_. z_]^2,z_]:=(2-Sqrt[2])/(Sqrt[\[Pi]] \[Alpha])/; Simplify[Positive[\[Alpha]]];
integrate[ Erfc[a_. z_]Erfc[b_. z_]Erfc[c_. z_], z_]:=1/(a Sqrt[\[Pi]])+1/(b Sqrt[\[Pi]])+1/(c Sqrt[\[Pi]])-(2 Sqrt[a^2+b^2] ArcTan[Sqrt[a^2+b^2]/c])/(a b \[Pi]^(3/2))-(2 Sqrt[a^2+c^2] ArcTan[Sqrt[a^2+c^2]/b])/(a c \[Pi]^(3/2))-(2 Sqrt[b^2+c^2] ArcTan[Sqrt[b^2+c^2]/a])/(b c \[Pi]^(3/2))/;
Simplify[Positive[a]&&Positive[b]&&Positive[c]];
integrate[ Erfc[a_. z_]^2 Erfc[b_. z_], z_]:=((a+2 b) \[Pi]-2 Sqrt[2] b ArcTan[(Sqrt[2] a)/b]-4 Sqrt[a^2+b^2] ArcTan[Sqrt[a^2+b^2]/a])/(a b \[Pi]^(3/2))/;
Simplify[Positive[a]&&Positive[b]];
integrate[Erfc[\[Alpha]_. z_]^3,z_]:=(3 (\[Pi]-2 Sqrt[2] ArcTan[Sqrt[2]]))/(\[Pi]^(3/2) \[Alpha])/; Simplify[Positive[\[Alpha]]];
integrate[Erfc[a_. z_]Erfc[b_. z_]Erfc[c_. z_] Erfc[d_. _], z_]:=1/(a Sqrt[\[Pi]])+1/(b Sqrt[\[Pi]])+1/(c Sqrt[\[Pi]])+1/(d Sqrt[\[Pi]])+1/(a b  \[Pi]^(3/2)) 2 Sqrt[a^2+b^2](ArcTan[(Sqrt[a^2+b^2] Sqrt[a^2+b^2+c^2+d^2])/(c d)]-ArcTan[Sqrt[a^2+b^2]/c]-ArcTan[Sqrt[a^2+b^2]/d]) +1/(a c  \[Pi]^(3/2)) 2 Sqrt[a^2+c^2] (ArcTan[(Sqrt[a^2+c^2] Sqrt[a^2+b^2+c^2+d^2])/(b d)]-ArcTan[Sqrt[a^2+c^2]/b]-ArcTan[Sqrt[a^2+c^2]/d])+1/(b c  \[Pi]^(3/2)) 2 Sqrt[b^2+c^2] (ArcTan[(Sqrt[b^2+c^2] Sqrt[a^2+b^2+c^2+d^2])/(a d)]-ArcTan[Sqrt[b^2+c^2]/a]-ArcTan[Sqrt[b^2+c^2]/d])+1/(a d  \[Pi]^(3/2)) 2 Sqrt[a^2+d^2] (ArcTan[(Sqrt[a^2+d^2] Sqrt[a^2+b^2+c^2+d^2])/(b c)]-ArcTan[Sqrt[a^2+d^2]/b]-ArcTan[Sqrt[a^2+d^2]/c])+1/(b d \[Pi]^(3/2)) 2 Sqrt[b^2+d^2]( ArcTan[(Sqrt[b^2+d^2] Sqrt[a^2+b^2+c^2+d^2])/(a c)]-ArcTan[Sqrt[b^2+d^2]/a]-ArcTan[Sqrt[b^2+d^2]/c])+1/(c d  \[Pi]^(3/2)) 2 Sqrt[c^2+d^2] (ArcTan[(Sqrt[c^2+d^2] Sqrt[a^2+b^2+c^2+d^2])/(a b)]-ArcTan[Sqrt[c^2+d^2]/a]-ArcTan[Sqrt[c^2+d^2]/b])/; Simplify[Positive[a]&&Positive[b]&&Positive[c]&&Positive[d]];
integrate[Erfc[\[Alpha]_. z_]^4,z_]:=(4 (\[Pi]+3 Sqrt[2] (-2 ArcTan[Sqrt[2]]+ArcTan[2 Sqrt[2]])))/(\[Pi]^(3/2) \[Alpha])/; Simplify[Positive[\[Alpha]]];
integrate[Erfc[a_. z_]^2 Erfc[b_. z_]^2, z_]:=2/(a Sqrt[\[Pi]])+2/(b Sqrt[\[Pi]])-(4 Sqrt[2] ArcTan[(Sqrt[2] a)/b])/(a \[Pi]^(3/2))-(4 Sqrt[2] ArcTan[(Sqrt[2] b)/a])/(b \[Pi]^(3/2))-(8 Sqrt[a^2+b^2] ArcTan[Sqrt[a^2+b^2]/a])/(a b \[Pi]^(3/2))+(2 Sqrt[2] ArcTan[(2 a Sqrt[a^2+b^2])/b^2])/(a \[Pi]^(3/2))-(8 Sqrt[a^2+b^2] ArcTan[Sqrt[a^2+b^2]/b])/(a b \[Pi]^(3/2))+(2 Sqrt[2] ArcTan[(2 b Sqrt[a^2+b^2])/a^2])/(b \[Pi]^(3/2))+(8 Sqrt[a^2+b^2] ArcTan[(Sqrt[2] (a^2+b^2))/(a b)])/(a b \[Pi]^(3/2))/; Simplify[Positive[a]&&Positive[b]];
integrate[Erfc[a_. z_]^3 Erfc[b_. z_], z_]:=1/(a b \[Pi]^(3/2)) (a \[Pi]+3 b \[Pi]-6 Sqrt[2] b ArcTan[Sqrt[2]]-6 Sqrt[2] b ArcTan[(Sqrt[2] a)/b]-12 Sqrt[a^2+b^2] ArcTan[Sqrt[a^2+b^2]/a]+6 Sqrt[2] b ArcTan[(Sqrt[2] Sqrt[3 a^2+b^2])/b]+6 Sqrt[a^2+b^2] ArcTan[Sqrt[3 a^4+4 a^2 b^2+b^4]/a^2])/; Simplify[Positive[a]&&Positive[b]];
integrate[Erfc[a_. z_]^2 Erfc[b_. z_]Erfc[c_. z_], z_]:=2/(a Sqrt[\[Pi]])+1/(b Sqrt[\[Pi]])+1/(c Sqrt[\[Pi]])+(2 Sqrt[2] (-ArcTan[(Sqrt[2] a)/b]-ArcTan[(Sqrt[2] a)/c]+ArcTan[(Sqrt[2] a Sqrt[2 a^2+b^2+c^2])/(b c)]))/(a \[Pi]^(3/2))+1/(a b \[Pi]^(3/2)) 4 Sqrt[a^2+b^2] (-ArcTan[Sqrt[a^2+b^2]/a]-ArcTan[Sqrt[a^2+b^2]/c]+ArcTan[(Sqrt[a^2+b^2] Sqrt[2 a^2+b^2+c^2])/(a c)])+1/(a c \[Pi]^(3/2)) 4 Sqrt[a^2+c^2] (-ArcTan[Sqrt[a^2+c^2]/a]-ArcTan[Sqrt[a^2+c^2]/b]+ArcTan[(Sqrt[a^2+c^2] Sqrt[2 a^2+b^2+c^2])/(a b)])+(2 Sqrt[b^2+c^2] (-2 ArcTan[Sqrt[b^2+c^2]/a]+ArcTan[(Sqrt[b^2+c^2] Sqrt[2 a^2+b^2+c^2])/a^2]))/(b c \[Pi]^(3/2))/; Simplify[Positive[a]&&Positive[b]&&Positive[c]];


(* ::Input::Initialization:: *)
integrate[OwenT[a_. z_, b_.],z_]:= 1/(2Sqrt[2\[Pi]]) b/(a Sqrt[1+b^2]);
integrate[Exp[-\[Alpha]_. (z_-x_.)^2]OwenT[\[Beta]_. z_, c_.], z_]:=Sqrt[\[Pi]]/(8 Sqrt[\[Alpha]]) (2/\[Pi] ArcTan[c] Erfc[-x Sqrt[\[Alpha]]]-Erfc[-x \[Beta] Sqrt[\[Alpha]/(2\[Alpha]+\[Beta]^2)]]+4 OwenT[x \[Beta] Sqrt[(2\[Alpha])/(2\[Alpha]+\[Beta]^2)],(Sqrt[2\[Alpha]] c)/Sqrt[2\[Alpha]+\[Beta]^2 (1+c^2)]]+8 OwenS[x \[Beta] Sqrt[(2\[Alpha])/(2\[Alpha]+\[Beta]^2)],(Sqrt[2\[Alpha]] c)/Sqrt[2\[Alpha]+\[Beta]^2 (1+c^2)],Sqrt[2 \[Alpha]+\[Beta]^2]/(c \[Beta])]);
integrate[Erfc[p_. z_] OwenT[a_. z_,b_.],z_]:=b/(2 a Sqrt[1+b^2] Sqrt[2 \[Pi]])+ArcTan[b]/(2 p \[Pi]^(3/2))-(b ArcTan[(Sqrt[2] p)/(a Sqrt[1+b^2])])/(Sqrt[2] a Sqrt[1+b^2] \[Pi]^(3/2))-(Sqrt[2p^2+a^2] ArcTan[(a b Sqrt[2p^2+a^2])/(a^2+2 p^2)])/(2 a p \[Pi]^(3/2))/; Simplify[Positive[p]];
integrate[OwenT[\[Alpha]_. z_, a_.] OwenT[\[Beta]_. z_, b_.],z_]:=Sqrt[2]/(8\[Pi]^(3/2)) (a /Sqrt[1+a^2] 1/\[Alpha] ArcTan[(b Sqrt[(1+a^2)]\[Alpha])/Sqrt[(1+a^2) \[Alpha]^2+(1+b^2) \[Beta]^2]]+b /Sqrt[1+b^2] 1/\[Beta] ArcTan[(a Sqrt[(1+b^2)]\[Beta])/Sqrt[(1+a^2) \[Alpha]^2+(1+b^2) \[Beta]^2]]-Sqrt[\[Alpha]^2+\[Beta]^2]/(\[Alpha] \[Beta]) ArcTan[(a b \[Alpha] \[Beta])/(Sqrt[\[Alpha]^2+\[Beta]^2] Sqrt[(1+a^2) \[Alpha]^2+(1+b^2) \[Beta]^2])]); 
integrate[OwenT[\[Alpha]_. z_, a_.]^2 ,z_]:= 1/(4 \[Pi]^(3/2) \[Alpha]) ((Sqrt[2] a ArcTan[a/Sqrt[2]])/Sqrt[1+a^2]-ArcTan[a^2/(2 Sqrt[1+a^2])]);
integrate[Erfc[p_. z_]Erfc[q_. z_]  OwenT[a_. z_,b_.],z_]:=1/(2 \[Pi]^(3/2)) ((1/p+1/q)ArcTan[b]+(Sqrt[2]b )/( a Sqrt[1+b^2] ) (ArcTan[(a Sqrt[1+b^2])/(Sqrt[2] p)]+ArcTan[(a Sqrt[1+b^2])/(Sqrt[2] q)]-ArcTan[(a Sqrt[1+b^2] q)/(p Sqrt[a^2 (1+b^2)+2 (p^2+q^2)])]-ArcTan[(a Sqrt[1+b^2] p)/(q Sqrt[a^2 (1+b^2)+2 (p^2+q^2)])])+Sqrt[a^2+2 p^2] /( a p ) (ArcTan[(Sqrt[2] a b q)/ Sqrt[(a^2+2 p^2) (a^2 (1+b^2)+2 (p^2+q^2))]]-ArcTan[(a b )/Sqrt[a^2+2 p^2]])+Sqrt[a^2+2 q^2]/( a q) (ArcTan[(Sqrt[2] a b p)/ Sqrt[(a^2+2 q^2) (a^2 (1+b^2)+2 (p^2+q^2))]]-ArcTan[(a b)/Sqrt[a^2+2 q^2]])- Sqrt[p^2+q^2] /(p q) ArcTan[(b Sqrt[2 (p^2+q^2)])/Sqrt[2 (p^2+q^2)+a^2 (1+b^2)]])/; Simplify[Positive[p]&&Positive[q]];
integrate[Erfc[p_. z_]^2 OwenT[a_. z_,b_.],z_]:=1/(2 \[Pi]^(3/2)) ((2 ArcTan[b])/p+(2 Sqrt[2] b (ArcTan[(a Sqrt[1+b^2])/(Sqrt[2] p)]-ArcTan[(a Sqrt[1+b^2])/Sqrt[a^2 (1+b^2)+4 p^2]]))/(a Sqrt[1+b^2])-(Sqrt[2] ArcTan[(2 b p)/Sqrt[a^2 (1+b^2)+4 p^2]])/p+1/(a p) 2 Sqrt[a^2+2 p^2] (-ArcTan[(a b)/Sqrt[a^2+2 p^2]]+ArcTan[(Sqrt[2] a b p)/Sqrt[(a^2+2 p^2) (a^2 (1+b^2)+4 p^2)]]))/; Simplify[Positive[p]]


(* ::Input::Initialization:: *)
integrate[OwenS[-\[Alpha]_. z_, b_., c_.],z_]:= 1/(2Sqrt[2] \[Pi]^(3/2) \[Alpha]) (ArcTan[c]-b/Sqrt[1+b^2] ArcTan[(b c)/Sqrt[1+b^2]])/; Simplify[Positive[\[Alpha]]];

integrate[OwenS[\[Alpha]_. z_, a_., b_.] Erfc[\[Beta]_. z_],z_]:=  1/(4 \[Pi]^(3/2)) (1/ \[Beta] ArcTan[b/Sqrt[1+a^2+a^2 b^2]]+Sqrt[\[Alpha]^2+2\[Beta]^2]/(\[Alpha] \[Beta] ) ArcTan[b Sqrt[(\[Alpha]^2+2 \[Beta]^2)/((1+a^2 (1+b^2)) \[Alpha]^2+2 \[Beta]^2)]]-Sqrt[2]/\[Alpha] ArcTan[b]+(Sqrt[2] a)/(\[Alpha] Sqrt[1+a^2]) (-ArcTan[Sqrt[1+(a^2) ] /(a b)]+ ArcTan[(a b \[Alpha]^2 Sqrt[1+a^2])/(Sqrt[2] \[Beta] Sqrt[(1+a^2 (1+b^2)) \[Alpha]^2+2 \[Beta]^2])]+ ArcTan[(Sqrt[2] \[Beta] Sqrt[1+a^2])/(a b  Sqrt[(1+a^2 (1+b^2)) \[Alpha]^2+2 \[Beta]^2])]))/; Simplify[Positive[\[Alpha]]&&Positive[\[Beta]]];
integrate[OwenS[\[Alpha]_. z_, a_., b_.] Erfc[\[Beta]_. z_],z_]:= integrate[1/(2\[Pi]) ArcTan[b/Sqrt[1+a^2+a^2 b^2]]Erfc[\[Beta] z]-OwenS[-\[Alpha] z, a, b]Erfc[\[Beta] z],z]/; Simplify[Negative[\[Alpha]]&&Positive[\[Beta]]];
